<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="DESKTOP-J0DQ7VP" name="com.Testing.Transform_demo" tests="8" failures="2" timestamp="2022-02-18T11:12:39 IST" time="0.172" errors="0">
  <testcase name="username" time="0.000" classname="com.Testing.Transform_demo">
    <failure type="java.lang.AssertionError" message="expected [smith] but found [starc]">
      <![CDATA[java.lang.AssertionError: expected [smith] but found [starc]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.Testing.Transform_demo.username(Transform_demo.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- username -->
  <system-out/>
  <testcase name="password" time="0.000" classname="com.Testing.Transform_demo">
    <skipped/>
  </testcase> <!-- password -->
  <system-out/>
  <testcase name="username" time="0.000" classname="com.Testing.Transform_demo">
    <skipped/>
  </testcase> <!-- username -->
  <system-out/>
  <testcase name="username" time="0.016" classname="com.Testing.Transform_demo">
    <skipped/>
  </testcase> <!-- username -->
  <system-out/>
  <testcase name="username" time="0.078" classname="com.Testing.Transform_demo">
    <skipped/>
  </testcase> <!-- username -->
  <system-out/>
  <testcase name="password" time="0.078" classname="com.Testing.Transform_demo">
    <skipped/>
  </testcase> <!-- password -->
  <system-out/>
  <testcase name="password" time="0.000" classname="com.Testing.Transform_demo">
    <skipped/>
  </testcase> <!-- password -->
  <system-out/>
  <testcase name="password" time="0.000" classname="com.Testing.Transform_demo">
    <failure type="java.lang.AssertionError" message="expected [smith@123] but found [starc@123]">
      <![CDATA[java.lang.AssertionError: expected [smith@123] but found [starc@123]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.Testing.Transform_demo.password(Transform_demo.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- password -->
  <system-out/>
</testsuite> <!-- com.Testing.Transform_demo -->
